### ISSUE TITLE
Captchas

### ISSUE THREAD

**Issue by sartika6** [infotrex/bulk-upload-to-opensea#66]
Is there any legit way to bypass captchas?

**Comment by sartika6** [comment]
I get mountains and stuff. Actually there is a way to put captcha recognition api inside python code but those apis are paid. Also there is sometimes cloudflare loading screen, probably no way to bypass that until code recognizes it and starts where it left off  from different tab.

**Comment by infotrex** [comment]
@sartika6 
i cannot bypass the captcha. sorry

**Comment by ZacharyAkers** [comment]
@sartika6 they started putting captcha up now? I haven't seen any yet

**Comment by misterkayr** [comment]
> @sartika6 they started putting captcha up now? I haven't seen any yet

Me either
And I have no idea what the mountain and cars comment is either.... Have I missed something?

**Comment by ZacharyAkers** [comment]
@infotrex If i saw captchas I might be able to bypass them in script by changing viewport size(sometimes changing viewport size bypasses captchas, but I need to get captcha to test it. Which I haven't received any yet.

**Comment by misterkayr** [comment]
Maybe Captcha is location specific, because I dont see any

**Comment by infotrex** [comment]
> @infotrex If i saw captchas I might be able to bypass them in script by changing viewport size(sometimes changing viewport size bypasses captchas, but I need to get captcha to test it. Which I haven't received any yet.

i just test on "import UserAgent fake_useragent", i not it can work or not. :)

**Comment by misterkayr** [comment]
> Hey any idea what we can do to solve the captcha ? Every 10 creation we need to click on „im not a robot“ .. and then we can continue with editing Start number at Python app.

Can we get a screenshot of what you are seeing?
I just uploaded 500 NFTs and it just finished 10 minutes ago, and not once, was there a captcha

**Comment by emrebaran** [comment]
![image](https://user-images.githubusercontent.com/98944150/153774881-a12faf7a-d26d-432c-a4f8-a58a432182f8.png)
@misterkayr

**Comment by misterkayr** [comment]
I would contact Opensea support and ask why this is happening, as it is something I have yet to see, and to be honest, I dont understand why you are getting it.
Better to get the issue solved at the source if you can

**Comment by emrebaran** [comment]
I did that two days ago, but still not get any respond from opensea. They made a tweet on Twitter about that and I think this will stay forever. Thanks for your help! 


Gesendet von Yahoo Mail für iPhone


Am Sonntag, Februar 13, 2022, 11:38 PM schrieb misterkayr ***@***.***>:




I would contact Opensea support and ask why this is happening, as it is something I have yet to see, and to be honest, I dont understand why you are getting it.
Better to get the issue solved at the source if you can

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ZacharyAkers** [comment]
only thing i can suggest for any captchas anyone gets is to download buster [https://chrome.google.com/webstore/detail/buster-captcha-solver-for/mpbjkejclgfgadiemmefgebjfooflfhl?hl=en](url)
Should solve any captchas you might have

**Comment by infotrex** [comment]
@ZacharyAkers
thank you for your suggestion.

**Comment by Intelligencybar** [comment]
After how many items did the captcha appear?

**Comment by kevin96vazquez** [comment]
> 

10 items

**Comment by infotrex** [comment]
> > 
> 
> 10 items

do you download I'm not robot captcha clicker extension link: https://chrome.google.com/webstore/detail/im-not-robot-captcha-clic/ceipnlhmjohemhfpbjdgeigkababhmjc/related?hl=en-US

**Comment by ZacharyAkers** [comment]
Only time the app will stop currently is if a image recaptcha pops up as long as you have latest upload18.py and the I'm not robot chrome extension.

**Comment by kevin96vazquez** [comment]
> > > 
> > 
> > 
> > 10 items
> 
> do you download I'm not robot captcha clicker extension link: https://chrome.google.com/webstore/detail/im-not-robot-captcha-clic/ceipnlhmjohemhfpbjdgeigkababhmjc/related?hl=en-US

Not really, but I'll try and let you know

**Comment by kevin96vazquez** [comment]
> > > 
> > 
> > 
> > 10 items
> 
> do you download I'm not robot captcha clicker extension link: https://chrome.google.com/webstore/detail/im-not-robot-captcha-clic/ceipnlhmjohemhfpbjdgeigkababhmjc/related?hl=en-US

![Screen](https://user-images.githubusercontent.com/99713243/154017992-2c5ee539-0c47-4e03-befb-ce514e959fdf.png)

When the captcha appears, the extension activates the button but does not select the images, the app (python upload18.py) stops anyway

**Comment by ZacharyAkers** [comment]
@kevin96vazquez buster is having issues, only way to solve images ATM is to do them manually. We could make it so it doesn't but the services to do that require to pay fees or will slow the process of uploading nfts tremendously as would have to constantly refresh browser while uploading

**Comment by ZacharyAkers** [comment]
As of moment as long as you are lucky with recaptcha you can upload as many as possible till you hir the image one, was able to hit couple hundred earlier just by having I'm not robot extension and new update. It's progress at least 😅

**Comment by Intelligencybar** [comment]
I found solution with image-recognize clicker

**Comment by ZacharyAkers** [comment]
@Intelligencybar can you link it?

**Comment by Kisnobeats** [comment]
> image-recognize clicker

Where is the link? Thank you!

**Comment by Intelligencybar** [comment]
@ZacharyAkers @Kisnobeats https://www.macrorecorder.com/
Enterprise version supports image recognition

**Comment by Intelligencybar** [comment]
I even set it to automatically reload the script in case the site throws a keyword error and it automatically changes the NFT start number in upload18 to continue on its own

**Comment by Kisnobeats** [comment]
> I even set it to automatically reload the script in case the site throws a keyword error and it automatically changes the NFT start number in upload18 to continue on its own

My Guy! Thank you for such a quick response and sharing this info with us. I will have to check this out and see if I can handle it. I'll come back here with updates.

**Comment by Amogha-Maiya** [comment]
we can use a combination of extension ......1)checks the "I AM not a Robot"(Already updated in code) 2) Solve Captcha using BUSTER EXTENSION ...........we need to update code such that it clicks on buster icon inside Captcha ...........continue to upload after this happens

**Comment by Kisnobeats** [comment]
> we can use a combination of extension ......1)checks the "I AM not a Robot"(Already updated in code) 2) Solve Captcha using BUSTER EXTENSION ...........we need to update code such that it clicks on buster icon inside Captcha ...........continue to upload after this happens

The issue I have with these extensions is that I install them, but when the script begins it opens up a chrome browser that does not have the extensions installed (for whatever reason that may be). I have no idea what to do about that issue.

**Comment by infotrex** [comment]
> we can use a combination of extension ......1)checks the "I AM not a Robot"(Already updated in code) 2) Solve Captcha using BUSTER EXTENSION ...........we need to update code such that it clicks on buster icon inside Captcha ...........continue to upload after this happens

Yes. Combinate Extension and script will bypass the captcha. Can you modify the script?

**Comment by Amogha-Maiya** [comment]
@infotrex @Kisnobeats 
i dont know selenium !!
May be if we could ask out somebody who knows selenium & Python very well.
By using Combinate of Extensions and script we can BYPASS the CAPTCHAS HOPEFULLY!!!

**Comment by ZacharyAkers** [comment]
@Amogha-Maiya I tried already its incredibly difficult to do, you can't directly click the button using script because the dev who made buster put a shadow root(close) which basically makes it nearly impossible to automate

**Comment by Amogha-Maiya** [comment]
@ZacharyAkers Ah okay!! Thanks for the info!

**Comment by ZacharyAkers** [comment]
> > we can use a combination of extension ......1)checks the "I AM not a Robot"(Already updated in code) 2) Solve Captcha using BUSTER EXTENSION ...........we need to update code such that it clicks on buster icon inside Captcha ...........continue to upload after this happens
> 
> The issue I have with these extensions is that I install them, but when the script begins it opens up a chrome browser that does not have the extensions installed (for whatever reason that may be). I have no idea what to do about that issue.

@Kisnobeats if you sign in to chrome on driver it'll have all extensions and automatically sign you in Everytime you you run the app.

**Comment by berkaytscc** [comment]
@ZacharyAkers Did you get any captcha verification?

**Comment by ZacharyAkers** [comment]
@berkaytscc yesterday i was getting image ones every 10 upload, haven't been on today to upload any yet due to working.

**Comment by berkaytscc** [comment]
will you fix the problem?

**Comment by ZacharyAkers** [comment]
@berkaytscc you have to download i'm not a robot extension, buster extension and set up a autoclicker to click the buster solver button, I can't really do much else to fix the captcha problems.

**Comment by nabeelsaleem** [comment]
> @berkaytscc you have to download i'm not a robot extension, buster extension and set up a autoclicker to click the buster solver button, I can't really do much else to fix the captcha problems.

Is your solution working, or you just giving idea?

**Comment by ZacharyAkers** [comment]
> 

Yea that works

**Comment by kaikecloss** [comment]
![image](https://user-images.githubusercontent.com/95150247/154784389-eb97062b-6870-42e5-a8a2-f8fa7be62300.png)
my recaptcha there is no option to select, does anyone already have a solution for this?

**Comment by saams4u** [comment]
> ![image](https://user-images.githubusercontent.com/95150247/154784389-eb97062b-6870-42e5-a8a2-f8fa7be62300.png) my recaptcha there is no option to select, does anyone already have a solution for this?

I'm getting the same problem
![Capture](https://user-images.githubusercontent.com/41460785/154784760-9e2f3412-0fc5-4106-abf5-f6cb9d6c42ed.PNG)
m

**Comment by emrebaran** [comment]
No more capchas opensea removed it

**Comment by esmalipo** [comment]
unfortunately recaptcha came back again

any way for solving it automaticly????

**Comment by Kisnobeats** [comment]
> unfortunately recaptcha came back again
> 
> any way for solving it automaticly????

The only way is to use the updated repository 1.5.8. The bot will open Chrome, log in, upload 1 NFT, close, and repeat until it's done. It will save a file for those it could not upload as well as a sales file if you chose to upload only.

**Comment by esmalipo** [comment]
> > unfortunately recaptcha came back again
> > any way for solving it automaticly????
> 
> The only way is to use the updated repository 1.5.8. The bot will open Chrome, log in, upload 1 NFT, close, and repeat until it's done. It will save a file for those it could not upload as well as a sales file if you chose to upload only.

Could you please explain more?

**Comment by Kisnobeats** [comment]
> > > unfortunately recaptcha came back again
> > > any way for solving it automaticly????
> > 
> > The only way is to use the updated repository 1.5.8. The bot will open Chrome, log in, upload 1 NFT, close, and repeat until it's done. It will save a file for those it could not upload as well as a sales file if you chose to upload only.
> 
> Could you please explain more?

Download the GITHub folder and extract it contents. You need to do this so that you are using the updated "main.py" file.

Then you would be able to use the script like you would normally. It will only upload 1 NFT piece at a time. 

Run script, opens browser (chrome), logs into Metamask, connects to Opensea, creates and upload NFT, closes everything and repeats the process

**Comment by nabeelsaleem** [comment]
Hi Dev,
Please check this one.

https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale

They save meta mask password and phrase in separate file, and do fresh login after each upload.
I think you should implement this method.

**Comment by Kisnobeats** [comment]
> Hi Dev,
> Please check this one.
> 
> https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale
> 
> They save meta mask password and phrase in separate file, and do fresh login after each upload.
> I think you should implement this method.

Yes, this is the one I use. My apologies, totally forgot I was in both issues board and replied not knowing this was not the Maxime GitHub.
